# Generated by Django 2.1.5 on 2020-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('n', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('watch', models.IntegerField()),
                ('ava', models.CharField(max_length=300)),
                ('urls', models.CharField(max_length=400)),
            ],
        ),
    ]