# Generated by Django 2.1.5 on 2020-06-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='urls',
        ),
    ]
